### ISSUE TITLE
Spot tracker: window frozen on save error

### ISSUE THREAD

**Issue by michele-riva** [viperleed/viperleed-imagej#1]
Dear Michael,

probably very easy to fix: I had a "disk full" error when trying to save data from the spot tracker (I was saving also the stack, and the disk was really full...). Somehow it now looks like the input widgets on the window (combos and buttons) are waiting for the saving to be over, and are thus disabled. I could still close the spot tracker window with the `More>>Reset all options & close`, so this part was not waiting. Probably this is just a matter to catching an exception.

**Comment by schmid-iap** [comment]
Tried also with the release version 1.00: No such problem any more, at least under Linux. One gets a "File saving error: No space left on device" error message, then the GUI elements of the spot tracker panel get enabled.
